update git hooks

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,4 +1,21 @@
 #!/usr/bin/env bash
+# inspired from https://github.com/diffplug/spotless/issues/178#issuecomment-351638034
 
 echo "==> Running the pre-commit git hook..."
-./gradlew spotlessApply check test
+
+# stash any unstaged changes
+git stash -q --keep-index
+
+# run the spotlessCheck with the gradle wrapper
+./gradlew spotlessCheck --daemon
+
+# store the last exit code in a variable
+RESULT=$?
+
+# unstash the unstashed changes
+git stash pop -q
+
+# return the './gradlew spotlessCheck' exit code
+exit $RESULT
+
+./gradlew check test
diff --git a/githooks/pre-push b/githooks/pre-push
--- a/githooks/pre-push
+++ b/githooks/pre-push
@@ -1,4 +1,19 @@
 #!/usr/bin/env bash
+# inspired from https://github.com/diffplug/spotless/issues/178#issuecomment-351638034
 
 echo "==> Running the pre-push git hook..."
-./gradlew spotlessCheck
+
+# stash any unstaged changes
+git stash -q --keep-index
+
+# run tests with the gradle wrapper
+./gradlew test --daemon
+
+# store the last exit code in a variable
+RESULT=$?
+
+# unstash the unstashed changes
+git stash pop -q
+
+# return the './gradlew test' exit code
+exit $RESULT
